# 6.	Загрузите набор данных о посетителях веб-сайта (например, набор данных Online Shoppers) и обучите модель классификации для предсказания, будет ли посетитель совершать покупку.

# Data Preparation

In [22]:
!pip3 install -U ucimlrepo
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

url = "https://archive.ics.uci.edu/static/public/468/data.csv"
df = pd.read_csv(url)

# transforming object types
label_encoder = LabelEncoder()
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = label_encoder.fit_transform(df[column])

#making task as binary classification
y = (df['Revenue']> np.median(df['Revenue'])).astype(int)
X = df.drop('Revenue', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# SVC

In [32]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
from sklearn.svm import SVC
model = SVC(kernel='linear', C=1)
model.fit(X_train, y_train)

SVCpred = model.predict(X_test)

print("Метрики качества:")
print(classification_report(y_test, SVCpred))

conf_matrix = confusion_matrix(y_test, SVCpred)
print("Матрица ошибок:")
print(conf_matrix)

SVCaccuracy = accuracy_score(y_test, SVCpred)
print(f"Точность модели: {SVCaccuracy}")

SVCROCAUS = roc_auc_score(y_test, SVCpred)
print(f"ROC AUS: {SVCROCAUS}")

Метрики качества:
              precision    recall  f1-score   support

           0       0.88      0.97      0.93      2055
           1       0.72      0.36      0.48       411

    accuracy                           0.87      2466
   macro avg       0.80      0.67      0.70      2466
weighted avg       0.86      0.87      0.85      2466

Матрица ошибок:
[[1996   59]
 [ 261  150]]
Точность модели: 0.870235198702352
ROC AUS: 0.6681265206812652


# KNN

In [33]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier()
model_knn.fit(X_train, y_train)
KNNpred = model_knn.predict(X_test)

print("Метрики качества:")
print(classification_report(y_test, KNNpred))

conf_matrix = confusion_matrix(y_test, KNNpred)
print("Матрица ошибок:")
print(conf_matrix)

KNNaccuracy = accuracy_score(y_test, KNNpred)
print(f"Точность модели: {KNNaccuracy}")

KNNROCAUS = roc_auc_score(y_test, KNNpred)
print(f"ROC AUS: {KNNROCAUS}")

Метрики качества:
              precision    recall  f1-score   support

           0       0.88      0.97      0.92      2055
           1       0.68      0.36      0.47       411

    accuracy                           0.87      2466
   macro avg       0.78      0.66      0.70      2466
weighted avg       0.85      0.87      0.85      2466

Матрица ошибок:
[[1986   69]
 [ 263  148]]
Точность модели: 0.8653690186536902
ROC AUS: 0.6632603406326034


# Naive Bayes

In [34]:
from sklearn.naive_bayes import GaussianNB

model_nb = GaussianNB()
model_nb.fit(X_train, y_train)
NBpred = model_nb.predict(X_test)

print("Метрики качества:")
print(classification_report(y_test, NBpred))

conf_matrix = confusion_matrix(y_test, NBpred)
print("Матрица ошибок:")
print(conf_matrix)

NBaccuracy = accuracy_score(y_test, NBpred)
print(f"Точность модели: {NBaccuracy}")

NBROCAUS = roc_auc_score(y_test, NBpred)
print(f"ROC AUS: {NBROCAUS}")

Метрики качества:
              precision    recall  f1-score   support

           0       0.93      0.81      0.87      2055
           1       0.42      0.69      0.52       411

    accuracy                           0.79      2466
   macro avg       0.68      0.75      0.69      2466
weighted avg       0.84      0.79      0.81      2466

Матрица ошибок:
[[1666  389]
 [ 127  284]]
Точность модели: 0.7907542579075426
ROC AUS: 0.7508515815085158


In [36]:
print('Top Accuracy')
acc = [SVCaccuracy, KNNaccuracy, NBaccuracy]
sorted_acc = sorted(acc, reverse=True)
method = ['SVC', 'KNN', 'NB']
result = list(zip(method, sorted_acc))

for variable, value in result:
    print(f'{variable}: {value}')

print('top ROCAUS')
rocaus = [SVCROCAUS, KNNROCAUS, NBROCAUS]
sorted_rocaus = sorted(rocaus, reverse=True)
method = ['SVC', 'KNN', 'NB']
result = list(zip(method, sorted_rocaus))

for variable, value in result:
    print(f'{variable}: {value}')

Top Accuracy
SVC: 0.870235198702352
KNN: 0.8653690186536902
NB: 0.7907542579075426
top ROCAUS
SVC: 0.7508515815085158
KNN: 0.6681265206812652
NB: 0.6632603406326034
